### ISSUE TITLE
encoder compatibility with Via

### ISSUE THREAD

**Issue by r4ph74** [victorlucachi/void16#1]
Hi Victor , 

I've been thinking, how to setup the encoder with VIA ? 

is the VIA already adopt the encoder capability?

**Comment by victorlucachi** [comment]
no, VIA Configurator does not have encoder support. Vial on the other hand does. I highly suggest going over the QMK Docs for all this info and more, including an answer to your question regarding the VOID9 name.

**Comment by r4ph74** [comment]
Thanks ... Victor .  I will have a more look at documentation ..
