### ISSUE TITLE
bought from your material list but the pro micro is not recognized, im wondering if you had the same issue?

### ISSUE THREAD

**Issue by Rikiar73574** [victorlucachi/void16#2]
i bought the 5v micro usb one by mistake but installing a lot of drivers i'm still unable to get it recognized.

**Comment by victorlucachi** [comment]
except for the usb port and layout differences, functionally they're all the same; the 3d models however are designed around the micro usb variant of the controller, which has 33mm in length.

having said that, I dont know what os you're using, but on windows qmk toolbox should install the required drivers; once you connect the controller to your computer in bootloader mode it should show up under com ports.

**Comment by Rikiar73574** [comment]
FYI, yes i noticed the usb-C variant was too long, but buying from your material list it appears that the aliexpress listing is wrong and they're actually selling a 32u4rc instead of a 32u4 which has no bootloader and is basically unusable without a programmer.
might want to note that.
