### ISSUE TITLE
How to solder ec11 to pro micro

### ISSUE THREAD

**Issue by vibetribe482** [victorlucachi/void16#4]
Hello! Can you please show how to solder encoder to pro micro? In your assembly guide there is only 2 pins, but encoder have 5 pins. Thank you.

**Comment by victorlucachi** [comment]
> Hello! Can you please show how to solder encoder to pro micro? In your assembly guide there is only 2 pins, but encoder have 5 pins. Thank you.

Hey, the two pins on the left are wired into the switch matrix, and on the right side the middle pin to ground, out A and out B to the pins mentioned in the pinout. Hope this makes things clearer. 

![image](https://github.com/victorlucachi/void16/assets/2669084/b05e0d2d-acc0-42de-865e-2e0e6728223d)

**Comment by vibetribe482** [comment]
Thank you for suck a quick response! Now it’s clear enough. Have a nice day!
